// <auto-generated />
using System;
using DAL.PlayLocal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.PlayLocal.Migrations
{
    [DbContext(typeof(PlayLocalDBcontext))]
    [Migration("20251202114411_FixNullableinplayer")]
    partial class FixNullableinplayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourtSportsType", b =>
                {
                    b.Property<string>("CourtsCourtID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportsTypesSportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourtsCourtID", "SportsTypesSportId");

                    b.HasIndex("SportsTypesSportId");

                    b.ToTable("CourtSports", (string)null);
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Booking", b =>
                {
                    b.Property<string>("BookingID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CourtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlayerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BookingID");

                    b.HasIndex("CourtID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Court", b =>
                {
                    b.Property<string>("CourtID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Is_Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("money");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VenueID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourtID");

                    b.HasIndex("VenueID");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.CourtPhoto", b =>
                {
                    b.Property<string>("PhotoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhotoID");

                    b.HasIndex("CourtID");

                    b.ToTable("CourtPhotos");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Owner", b =>
                {
                    b.Property<string>("OwnerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("OwnerID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Player", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hobby")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.SportsType", b =>
                {
                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SportId");

                    b.ToTable("SportsTypes");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Venue", b =>
                {
                    b.Property<string>("VenueID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GoogleMapsLink")
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasEquipmentRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MainContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VenueID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.VenueWorkingHours", b =>
                {
                    b.Property<string>("VenueWorkingHoursID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("VenueID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VenueWorkingHoursID");

                    b.HasIndex("VenueID");

                    b.ToTable("VenueWorkingHours");
                });

            modelBuilder.Entity("CourtSportsType", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtsCourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.PlayLocal.Models.SportsType", null)
                        .WithMany()
                        .HasForeignKey("SportsTypesSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Booking", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.PlayLocal.Models.Player", "Player")
                        .WithMany("Bookings")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Court", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.CourtPhoto", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Court", "Court")
                        .WithMany("CourtPhotos")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Venue", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Owner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.VenueWorkingHours", b =>
                {
                    b.HasOne("DAL.PlayLocal.Models.Venue", "Venue")
                        .WithMany("VenueWorkingHours")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CourtPhotos");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Owner", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Player", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.PlayLocal.Models.Venue", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("VenueWorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
