// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayLocal_EF.Data.Contexts;

#nullable disable

namespace PlayLocal_EF.Data.Migrations
{
    [DbContext(typeof(PlayLocalDBcontext))]
    [Migration("20251123145317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourtSportsType", b =>
                {
                    b.Property<string>("CourtsCourtID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SportsTypesSportId")
                        .HasColumnType("int");

                    b.HasKey("CourtsCourtID", "SportsTypesSportId");

                    b.HasIndex("SportsTypesSportId");

                    b.ToTable("CourtSports", (string)null);
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Court", b =>
                {
                    b.Property<string>("CourtID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Is_Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("money");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VenueID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourtID");

                    b.HasIndex("VenueID");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.CourtPhoto", b =>
                {
                    b.Property<string>("PhotoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PhotoID");

                    b.HasIndex("CourtID");

                    b.ToTable("CourtPhotos");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Owner", b =>
                {
                    b.Property<string>("OwnerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("OwnerID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.SportsType", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SportId");

                    b.ToTable("SportsTypes");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Venue", b =>
                {
                    b.Property<string>("VenueID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CloseDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("Time");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GoogleMapsLink")
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasEquipmentRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MainContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("Time");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VenueID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.VenueService", b =>
                {
                    b.Property<string>("ServiceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VenueID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ServiceID");

                    b.HasIndex("VenueID");

                    b.ToTable("VenueServices");
                });

            modelBuilder.Entity("CourtSportsType", b =>
                {
                    b.HasOne("PlayLocal_EF.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtsCourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayLocal_EF.Entities.SportsType", null)
                        .WithMany()
                        .HasForeignKey("SportsTypesSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Court", b =>
                {
                    b.HasOne("PlayLocal_EF.Entities.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.CourtPhoto", b =>
                {
                    b.HasOne("PlayLocal_EF.Entities.Court", "Court")
                        .WithMany("CourtPhotos")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Venue", b =>
                {
                    b.HasOne("PlayLocal_EF.Entities.Owner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.VenueService", b =>
                {
                    b.HasOne("PlayLocal_EF.Entities.Venue", "Venue")
                        .WithMany("VenueServices")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Court", b =>
                {
                    b.Navigation("CourtPhotos");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Owner", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("PlayLocal_EF.Entities.Venue", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("VenueServices");
                });
#pragma warning restore 612, 618
        }
    }
}
